version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "lew_kianapp"
    environment:
      - INPUT_DIR=/data/input
      - OUTPUT_DIR=/data/output
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output
